export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCESS';

export const EMAIL_LOGIN = 'EMAIL_LOGIN';
export const EMAIL_LOGIN_SUCCESS = 'EMAIL_LOGIN_SUCCESS';
export const EMAIL_LOGIN_FAILED = 'EMAIL_LOGIN_FAILED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_SUCCESS = 'SET_CATEGORIES_SUCCESS';
export const SET_CATEGORIES_FAILED = 'SET_CATEGORIES_FAILED';

export const REMOVE_CATEGORIES = 'REMOVE_CATEGORIES';
export const REMOVE_CATEGORIES_SUCCESS = 'REMOVE_CATEGORIES_SUCCESS';
export const REMOVE_CATEGORIES_FAILED = 'REMOVE_CATEGORIES_FAILED';

export const ADD_PRODUCTS = 'ADD_PRODUCT';
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCTS_FAILED = 'ADD_PRODUCT_FAILED';
